spring:
  application:
    name: ${APP_NAME}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop #change to VALIDATE if in production
  docker:
    compose:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USER}
    password: ${DB_PASSWORD}
