spring:
  application:
    name: fluffy
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop #change to VALIDATE if in production
  docker:
    compose:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  token:
    expired-time-minutes: ${TOKEN_EXPIRED_TIME_MINUTES}
  mail:
    name: "Fluffy"
    subject: "Confirm your email"
    message: |
      Thank you for registration. 
      Your code:
      %s
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  auth:
    message: "A confirmation code has been sent to your email address. Please note that this code will expire in 15 minutes"
                
